### PR TITLE
Ben's contribution.

### PR DESCRIPTION
**Pull request by Gemsbane**
Created MarkDown file as per instructed. Took the opportunity to find the secret code too, and decided to take a dump on @KarlTilsner 's work because what else are best friends for.

### CODE REVIEW

**Comment by KarlTilsner** [comment]
Ban this man at all costs

**Comment by Gemsbane** [comment]
I'm too dangerous to be left alive!

**Comment by KarlTilsner** [comment]
He is a threat so society

**Comment by Zec-Wicks** [comment]
Looks good to me ✨

**Pull request merged**
